CRM_ImapX/Controllers/MailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRM_ImapX.Services;
using CRM_ImapX.Models.ViewModels;
using System.IO;


namespace CRM_ImapX.Controllers
{
    public class MailController : Controller
    {
        // GET: Mail
        public ActionResult Index(MailPagedListViewModel model)
        {
            if (model.PageSize == 0)
            {
                model.PageSize = 10;
            }
           
            var service = new MailService();
            service.ReciveUnseenImap();

            var result = service.ListofMails("michal.latka@4kprojekt.pl", model.PageNumber, model.PageSize);
            var receivedMails = new MailPagedListViewModel();
            receivedMails.ResultList = new List<MailReceiveViewModel>();
          
            foreach (var i in result.ResultList)
            {
                var rMail = new MailReceiveViewModel();


                rMail.MessageID = i.messageID;
                rMail.MessageGuid = i.messageGuid;
                rMail.Subject = i.subject;
                rMail.From = i.from;
                rMail.To = i.to;
                rMail.Cc = i.cc;
                rMail.Bcc = i.bcc;
                rMail.Date = i.date;
                rMail.Text = i.text;
                rMail.Html = i.html;
                rMail.isRead = i.isRead;
                rMail.haveAttachments = i.haveAttachment;
               
                receivedMails.ResultList.Add(rMail);
                
                
            }

            receivedMails.PageSize = model.PageSize;
            receivedMails.TotalRecords = result.TotalRecords;
         
            return View(receivedMails);

            
        }


        public ActionResult Show(CRM_ImapX.Models.ViewModels.MailReceiveViewModel model)
        {

            var service = new MailService();
            var result = service.ShowMail(model.MessageGuid);
            var messageContent = service.GetMessageContent(result.date, model.MessageGuid);
            var ListOfAttachments = service.DisplayAttachments(model.MessageGuid);


            var mailMessageVM = new MailReceiveViewModel();
            mailMessageVM.From = result.from;
            mailMessageVM.Subject = result.subject;
            mailMessageVM.MessageGuid = result.messageGuid;
            mailMessageVM.To = result.to;
            mailMessageVM.Cc = result.cc;
            mailMessageVM.Text = messageContent;
            mailMessageVM.paths = new List<string>();
            mailMessageVM.attachmentsNames = new List<string>();
            foreach (var i in ListOfAttachments)
            {
                string singlePath = Properties.Settings.Default.MailDirectory + "\\" + i.attachmentDate + "\\" + model.MessageGuid;

                mailMessageVM.paths.Add(singlePath);
                mailMessageVM.attachmentsNames.Add(i.attachmentName);

            }

            return View(mailMessageVM);
        }
        public ActionResult Download(string path, string filename)
        {

            byte[] fileBytes = System.IO.File.ReadAllBytes(path + "\\" + filename);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, filename);
        }


    }
}

CRM_ImapX/Controllers/MailSendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRM_ImapX.Services;
using CRM_ImapX.Models.ViewModels;
using System.IO;

namespace CRM_ImapX.Controllers
{
    public class MailSendController : Controller
    {
        // GET: MailSend

        public ActionResult IndexSentMails(MailPagedListViewModel model)
        {
            if (model.PageSize == 0)
            {
                model.PageSize = 10;
            }
                        
            var service = new sendMailService();
            var service2 = new MailService();
            var result = service.ListofSentMails("michal.latka@4kprojekt.pl", model.PageNumber, model.PageSize);

            var SentMails = new MailPagedListViewModel();
            SentMails.ResultList = new List<MailReceiveViewModel>();
          //  var listofMails = service2.importMailsFromXML(result);

            foreach (var i in result.ResultList)
            {
                var sentMail = new MailReceiveViewModel();

                sentMail.MessageID = i.messageID;
                sentMail.MessageGuid = i.messageGuid;
                sentMail.Subject = i.subject;
                sentMail.From = i.from;
                sentMail.To = i.to;
                sentMail.Cc = i.cc;
                sentMail.Bcc = i.bcc;
                sentMail.Date = i.date;
                sentMail.Text = i.text;
                sentMail.Html = i.html;
                sentMail.haveAttachments = i.haveAttachment;
                sentMail.isRead = i.isRead;

                SentMails.ResultList.Add(sentMail);
            }
            SentMails.PageSize = model.PageSize;
            SentMails.TotalRecords = result.TotalRecords;

            return View(SentMails);
        }

        public ActionResult Index()
        {


            return View();
        }

        [HttpPost]
        public ActionResult sendMail(CRM_ImapX.Models.ViewModels.sendMailViewModel model)
        {
            var service = new sendMailService();
            var uploadedFiles = new List<CRM_ImapX.Models.Api.FileDTO>();
            foreach (var file in model.Upload)
            {
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    uploadedFiles.Add(new CRM_ImapX.Models.Api.FileDTO
                    {
                        Content = binaryReader.ReadBytes(file.ContentLength),
                        Name = file.FileName
                    });
                }
            }


            service.sendEmail(Properties.Settings.Default.Login, model.To, model.Subject, model.Content, model.Cc, model.Bcc, uploadedFiles, model.messageGuid);

            return RedirectToAction("Index");
        }


        [HttpGet]

        public ActionResult ReplayTo(CRM_ImapX.Models.ViewModels.MailReceiveViewModel model)
        {

            var service = new ReplyForwardService();
            var mailService = new MailService();
            var result = service.GetReplayTo(model.MessageGuid);

            var mailReplayVM = new sendMailViewModel();
            mailReplayVM.Date = result.date.ToString();
            DateTime enteredDate = DateTime.Parse(mailReplayVM.Date);
            var content = mailService.GetMessageContent(enteredDate, model.MessageGuid);

            if (result.from.Contains("<"))
            {

                var input = result.from.Substring(result.from.IndexOf("<") + 1);
                input = input.Substring(0, input.LastIndexOf(">"));
                mailReplayVM.To = input;
            }
            else
            {
                mailReplayVM.To = result.from;

            }



            mailReplayVM.Content = result.date + " " + result.from + Environment.NewLine + content;
            mailReplayVM.Subject = "Re:" + " " + result.subject;
            mailReplayVM.messageGuid = result.messageGuid;
            mailReplayVM.Cc = result.cc;
            mailReplayVM.Bcc = result.bcc;


            return View(mailReplayVM);
        }

        [HttpGet]
        public ActionResult ForwardTo(CRM_ImapX.Models.ViewModels.MailReceiveViewModel model)
        {
            var service = new ReplyForwardService();
            var mailService = new MailService();
            var result = service.GetReplayTo(model.MessageGuid);

            var mailForwardVM = new sendMailViewModel();
            mailForwardVM.Date = result.date.ToString();
            DateTime enteredDate = DateTime.Parse(mailForwardVM.Date);
            var content = mailService.GetMessageContent(enteredDate, model.MessageGuid);



            mailForwardVM.Content = result.date + " " + result.from + Environment.NewLine + content;
            mailForwardVM.Subject = "Fwd:" + " " + result.subject;
            mailForwardVM.messageGuid = result.messageGuid;
            mailForwardVM.Cc = result.cc;
            mailForwardVM.Bcc = result.bcc;

            return View(mailForwardVM);
        }


    }
}

CRM_ImapX/Views/MailSend/ForwardTo.cshtml
@model CRM_ImapX.Models.ViewModels.sendMailViewModel

@{
    ViewBag.Title = "Forward To";
}

<h2>Prześlij do</h2>

@using (Html.BeginForm("sendMail", "MailSend", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.To, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.To, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Cc, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Cc, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Bcc, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Bcc, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Subject, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
        </div>
    </div>

    <div class="editor-label">

        @Html.LabelFor(m => m.Content)
    </div>
    <div class="editor-field">
        @Html.TextAreaFor(m => m.Content, new { @class = "tinymce" })
        @Html.ValidationMessageFor(m => m.Content)
    </div>




    <h2>Załączniki</h2>

    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.Upload, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input type="file" name="upload" />
        </div>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.Upload, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input type="file" name="upload" />
        </div>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.Upload, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input type="file" name="upload" />
        </div>
    </div>

    <br />
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Wyślij" />
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript" src="~/Scripts/tinymce/tinymce.js">
    </script>

    <script type="text/javascript">
    tinymce.init({
        selector: ".tinymce",
        theme: "modern",
        valid_elements: '*[*]',
        width: 500,
        height: 300,
        menubar: false,
        resize: false,
        statusbar: false,

        plugins: ["advlist autolink lists charmap preview hr anchor",
            "pagebreak code nonbreaking table contextmenu directionality paste"],
        toolbar1: "styleselect | bold italic underline | pagebreak code preview | undo redo",
        toolbar2: "alignleft aligncenter alignright alignjustify | bullist numlist outdent indent"
    });
    </script>
}

CRM_ImapX/Views/MailSend/Index.cshtml
@model CRM_ImapX.Models.ViewModels.sendMailViewModel
@{
    ViewBag.Title = "sendMail";
}

<h2>Wyślij wiadomość.</h2>

@using (Html.BeginForm("sendMail", "MailSend", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="col-lg-8 col-lg-offset-2">
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.To, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.To, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Cc, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Cc, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Bcc, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Bcc, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Subject, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
            </div>
        </div>
        <div class="editor-label">
            @Html.LabelFor(m => m.Content)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(m => m.Content, new { @class = "tinymce" })
            @Html.ValidationMessageFor(m => m.Content)
        </div>

    </div>
    <div class="col-lg-4 col-lg-offset-2">
        <h2>Załączniki</h2>

        <br />
        <div class="form-group">
            @Html.LabelFor(m => m.Upload, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <input type="file" name="upload" />
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(m => m.Upload, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <input type="file" name="upload" />
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(m => m.Upload, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                <input type="file" name="upload" />
            </div>
        </div>
        <br />
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Wyślij" />
            </div>
        </div>
    </div>
}


@section Scripts {
   @Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript" src="~/Scripts/tinymce/tinymce.js">
</script>

<script type="text/javascript">
    tinymce.init({
        selector: ".tinymce",
        theme: "modern",
        valid_elements: '*[*]',
        width: 500,
        height: 300,
        menubar: false,
        resize: false,
        statusbar: false,

        plugins: ["advlist autolink lists charmap preview hr anchor",
            "pagebreak code nonbreaking table contextmenu directionality paste"],
        toolbar1: "styleselect | bold italic underline | pagebreak code preview | undo redo",
        toolbar2: "alignleft aligncenter alignright alignjustify | bullist numlist outdent indent"
    });
</script>
}

CRM_ImapX/Views/MailSend/IndexSentMails.cshtml
@using System.Runtime.InteropServices
@model CRM_ImapX.Models.ViewModels.MailPagedListViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>



<table class="table">

    <tr>
        <th>
            Od
        </th>

        <th>
            Data
        </th>

        <th>
            Do
        </th>

        <th>
            Cc
        </th>

        <th>
            Bcc
        </th>

        <th>
            Temat
        </th>

        @foreach (var item in Model.ResultList)
        {

        <tr onclick="location.href='@Url.Action("Show", "Mail", new { messageGuid = item.MessageGuid})'">


            <td>
                @Html.DisplayFor(modelItem => item.From)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.To)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bcc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @if (item.haveAttachments == true)
                {
                    <img src="@Url.Content("~/Inventory/icon-attachment-32x321.png")" alt="" />
                }
            </td>
           



        </tr>

    }



</table>
<br />
<p>Ilość rekordów: @Model.TotalRecords</p><br />

@for (int i = 0; i <= Model.TotalRecords / Model.PageSize; i++)
{
    <a href="?PageNumber=@i&PageSize=@Model.PageSize">@(i + 1)</a>
}

CRM_ImapX/Views/MailSend/ReplayTo.cshtml
@model CRM_ImapX.Models.ViewModels.sendMailViewModel
@{
    ViewBag.Title = "sendMail";
}

<h2>Wyślij nową wiadomość</h2>

@using (Html.BeginForm("sendMail", "MailSend", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.To, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.To, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Cc, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Cc, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Bcc, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Bcc, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Subject, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
        </div>
    </div>
    <div class="editor-label">
        @Html.LabelFor(m => m.Content)
    </div>
    <div class="editor-field">
        @Html.TextAreaFor(m => m.Content, new { @class = "tinymce" })
        @Html.ValidationMessageFor(m => m.Content)
    </div>




    <h2>Załączniki</h2>

    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.Upload, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input type="file" name="upload" />
        </div>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.Upload, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input type="file" name="upload" />
        </div>
    </div>
    <br />
    <div class="form-group">
        @Html.LabelFor(m => m.Upload, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            <input type="file" name="upload" />
        </div>
    </div>
    <br />
    <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Wyślij" />
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript" src="~/Scripts/tinymce/tinymce.js">
    </script>

    <script type="text/javascript">
    tinymce.init({
        selector: ".tinymce",
        theme: "modern",
        valid_elements: '*[*]',
        menubar: false,
        width: 500,
        height: 300,
        resize: false,
        statusbar: false,
        plugins: ["advlist autolink lists charmap preview hr anchor",
            "pagebreak code nonbreaking table contextmenu directionality paste"],
        toolbar1: "styleselect | bold italic underline | pagebreak code preview | undo redo",
        toolbar2: "alignleft aligncenter alignright alignjustify | bullist numlist outdent indent"
    });
    </script>
}